### PR TITLE
proposing a community of practice roadmap

### PR DESCRIPTION
**Pull request by quaid**
- builds from the idea of /sre becoming the home to an external community of practice
- as a placeholder and initial proposal it is called "SIG SRE"
- it contains all the work done to date by the SRE team from Red Hat
- it includes some visions I've heard from others or envisioned myself

### CODE REVIEW

**Comment by jeremyeder** [comment]
lgtm

**Comment by quaid** [comment]
> lgtm

Can you repeat with the magic slash please?

**Review by schwesig — COMMENTED** [review]
/lgtm
/approve

**Comment by hlipsig** [comment]
Lgtm

**Pull request merged**
