### PR TITLE
Fix a typo and reorder the introduction of SLO and SLI

### PR DESCRIPTION
**Pull request by bparees**
In my mind, service level indicators come first (that's the metric you're recording about the system) and service level objectives are defined in terms of those SLIs.  So I'm proposing this reordering and slight rewording.

Also fixing a small typo.

### CODE REVIEW

**Comment by bparees** [comment]
@jeremyeder ptal

**Comment by bparees** [comment]
@david-martin wdyt?

**Comment by david-martin** [comment]
Thanks @bparees 👍

**Pull request merged**
