### PR TITLE
Create OWNERS

### PR DESCRIPTION
**Pull request by david-martin**
For tide integration.
Based on contributors & reviewers so far

### CODE REVIEW

**Comment by david-martin** [comment]
fyi @amfred

**Comment by lisa** [comment]
@david-martin Should we heed the bot and ensure folks are members of the org?

**Comment by quaid** [comment]
> @david-martin Should we heed the bot and ensure folks are members of the org?

Do let's! The process and reasons why are in this part of the Community Handbook:

https://github.com/operate-first/common/blob/main/docs/add_gh_member_and_access.md

(We are working on converting the Community Handbook into a Jupyter notebook, so it's the repo link for now.)

IIRC, the process is automated once a maintainer merges the changes to the `common/github_config.yaml`. To expedite, we can ping one of the maintainers in Slack when the PRs are ready.

To @lisa's question, I think you can merge this PR but every additional PR on the repo will generate the same blocking error until everyone in the `owners` file is an org member.

**Comment by david-martin** [comment]
@chaitanyaenr @brizrobbo @billmvt @mh21 @amfred
If you'd like be added to the owners file for this repo, check for a recent invite to the operate-first github org.
It would be great to have you as reviewers, given your contributions already to the maturity phases.

**Comment by amfred** [comment]
Fixed on my part. Thanks.

**Review by mmazur — APPROVED** [review]

**Comment by david-martin** [comment]
Merging manually to get an OWNERS file in place

**Pull request merged**
